// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRZ13u0QXurUwLpY9AjJbrgfiVbAzxe20',
    appId: '1:373844020356:web:6d85827787bb359e6bc6d1',
    messagingSenderId: '373844020356',
    projectId: 'coinswitch-cd91a',
    authDomain: 'coinswitch-cd91a.firebaseapp.com',
    storageBucket: 'coinswitch-cd91a.appspot.com',
    measurementId: 'G-MFJSKEHQ5P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB18jejym-h6kkP3Cx9HeholaI2eOBThrA',
    appId: '1:373844020356:android:76e6657a22b673446bc6d1',
    messagingSenderId: '373844020356',
    projectId: 'coinswitch-cd91a',
    storageBucket: 'coinswitch-cd91a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpjF9j4oGz-cHmeGLCcn-WWnhA49NKmZc',
    appId: '1:373844020356:ios:62009e9d83d52bdb6bc6d1',
    messagingSenderId: '373844020356',
    projectId: 'coinswitch-cd91a',
    storageBucket: 'coinswitch-cd91a.appspot.com',
    iosClientId: '373844020356-hmrndnkr6rdegqc9br271dcq2ue0k5g3.apps.googleusercontent.com',
    iosBundleId: 'com.example.coinbase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpjF9j4oGz-cHmeGLCcn-WWnhA49NKmZc',
    appId: '1:373844020356:ios:62009e9d83d52bdb6bc6d1',
    messagingSenderId: '373844020356',
    projectId: 'coinswitch-cd91a',
    storageBucket: 'coinswitch-cd91a.appspot.com',
    iosClientId: '373844020356-hmrndnkr6rdegqc9br271dcq2ue0k5g3.apps.googleusercontent.com',
    iosBundleId: 'com.example.coinbase',
  );
}
